# Generated by Django 4.1 on 2022-08-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ACAO", "Ação"),
                    ("DRAMA", "Drama"),
                    ("FICCAO", "Ficção"),
                    ("OUTROS", "Outros"),
                ],
                max_length=15,
            ),
        ),
    ]
